const SUPABASE_URL = 'https://knormndeorczxgwqvkol.supabase.co';
const SUPABASE_KEY = 'sb_publishable_Dx6cuRP7CgJUwQlj67OFyQ_viNQ1SyL';
const { createClient } = window.supabase;
const db = createClient(SUPABASE_URL, SUPABASE_KEY);
const app = document.querySelector('#app');

const logo = `<img src="/assets/isang-eng-logo.png" alt="ISANG ENG 이상이엔지" class="logo">`;
const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav = () => `<header><a href="/"><img src="/assets/isang-eng-logo.png" alt="ISANG ENG 이상이엔지" class="logo"></a><nav><a href="/">홈</a><a href="/about">회사 소개</a><a href="/business">사업 소개</a><a href="/projects">시공 사례</a><a href="/contact">문의하기</a><a class="admin-nav" href="/admin.html">관리자</a></nav></header>`;
const toast = msg => { const el = document.createElement('div'); el.className='toast'; el.textContent=msg; document.body.appendChild(el); setTimeout(()=>el.remove(), 3200); };

async function projects() {
  const { data, error } = await db.from('projects').select('*').order('year',{ascending:false}).limit(100);
  if (error) throw error; return data || [];
}

function layout(content) { app.innerHTML = nav() + `<main>${content}</main><footer><div class="footer-inner"><div><img src="/assets/isang-eng-logo.png" alt="ISANG ENG 이상이엔지" class="footer-logo"><p>냉난방 공조와 크린룸을 위한<br>엔지니어링 파트너</p></div><div><span class="footer-label">NAVIGATION</span><a href="/">홈</a><a href="/about">회사 소개</a><a href="/business">사업 소개</a><a href="/projects">시공 사례</a><a href="/contact">문의하기</a></div><div><span class="footer-label">CONTACT</span><span>TEL<br>042-564-2223</span><span>EMAIL<br>isang@isang.co.kr</span><span>ADDRESS<br>대전광역시 서구 관저동<br>1969-10, 2F</span></div></div><div class="footer-bottom">© ${new Date().getFullYear()} ISANG ENG. All rights reserved.<span>HVAC &amp; CLEANROOM ENGINEERING</span></div></footer>`; }

async function renderHome() {
  layout(`<section class="hero"><div><p class="eyebrow">HVAC · CLEANROOM · ENGINEERING</p><h1>정밀한 기술로<br><strong>더 나은 환경</strong>을 만듭니다.</h1><p class="lead">냉난방 공조와 크린룸 설계·시공 전문기업 이상이엔지입니다.</p><a class="button" href="#/contact">견적문의하기</a></div><div class="hero-card"><span>01</span><b>Precision<br>Engineering</b><small>설계부터 시공, 유지관리까지</small></div></section><section class="section"><p class="eyebrow">WHAT WE DO</p><h2>공간의 기준을 설계합니다</h2><div class="cards"><article><b>HVAC</b><p>쾌적하고 안정적인 냉난방 공조 시스템</p></article><article><b>CLEANROOM</b><p>산업별 요구조건에 맞춘 크린룸 엔지니어링</p></article><article><b>PROJECT</b><p>현장 경험과 데이터로 완성하는 시공</p></article></div></section>`);
}

async function renderProjects() {
  try { const rows = await projects(); layout(`<section class="page-head"><p class="eyebrow">PROJECTS</p><h1>시공사례</h1><p>이상이엔지가 완성한 주요 프로젝트입니다.</p></section><section class="project-grid">${rows.length ? rows.map(x=>`<article class="project"><div class="project-no">${esc(x.year||'—')}</div><h3>${esc(x.name)}</h3><p>${esc(x.client||'')} ${x.location?`· ${esc(x.location)}`:''}</p><small>${esc(x.project_type||'')} ${x.grade?`· ${esc(x.grade)}`:''}</small><div>${esc(x.description||'')}</div></article>`).join('') : '<div class="empty">등록된 시공사례가 없습니다.</div>'}</section>`); }
  catch(e) { layout(`<section class="page-head"><h1>시공사례</h1><div class="error">데이터를 불러오지 못했습니다. Supabase 설정을 확인해 주세요.</div></section>`); }
}

const businessData = {
  cleanroom:{label:'Industrial & Bio Cleanroom',title:'Class 1,000 ~ 100,000 고청정 클린룸 엔지니어링',desc:'반도체, 광학 소자, 정밀 전자부품 및 GMP 의약품·의료기기 제조라인을 위한 청정 시스템을 구축합니다. 차압 계통 설계, FFU/EFU 유닛 제어 및 에어샤워·패스박스 연동 기류 최적화를 실현합니다.',features:[['정밀 차압 댐퍼 제어','실간 양압/음압 유지로 오염 물질 유입 차단'],['HEPA/ULPA FFU 유닛','99.99% 이상의 고효율 집진 및 저소음 설계']],spec:[['청정도 등급','ISO 14644 Class 6~8 / KGMP'],['온습도 제어','22 ± 1°C / 45 ± 5% RH'],['필터 효율','HEPA 99.97% ~ ULPA 99.999%'],['실내 차압 제어','+10Pa ~ +25Pa 차압 유지']],accent:'blue',cta:'클린룸 도면 검토 및 부하 계산 요청'},
  dryroom:{label:'Secondary Battery Dry Room',title:'노점온도 -40°C ~ -60°C 초저습 드라이룸 시스템',desc:'이차전지 리튬이온 배터리 전극·조립 라인 및 전고체 배터리 파일럿 라인을 위한 초저습 공조 환경을 완성합니다. 제습로터와 완벽한 기밀 용접 덕트 기술로 미세 수분을 원천 차단합니다.',features:[['용접 덕트 & 마스틱 밀폐','외부 수분 침투를 방지하는 밴드 마감 기밀'],['초저노점 연속 운전','폐열 회수형 고효율 제습 시스템 채용']],spec:[['보증 노점온도','D.P. -40°C ~ -60°C'],['덕트 시공 방식','Airtight Welding + Mastic Seal'],['외기 도입 시스템','Pre-Cooling Coil + Rotor 2단'],['판넬 사양','불연 우레탄/글라스울 기밀 패널']],accent:'teal',cta:'드라이룸 기술 사양 문의'},
  ref:{label:'Refrigeration & Cold Storage',title:'고효율 산업용 냉동 플랜트 & 저온 저장 설비',desc:'식품·의약품 저온 물류 및 고발열 원료 입고 보관을 위한 냉동 시스템입니다. 독일 비처(Bitzer) 2단 압축기와 대용량 살수 제상 자동화 탱크 설계로 안정적인 고내 온도를 유지합니다.',features:[['워터 디프로스트 자동화','빠른 서리 제거 및 제상수 회수 드레인 설계'],['비처(Bitzer) 2단 압축','-18°C ~ -40°C 급속 동결 및 초저온 보관']],spec:[['설계 고내 온도','-18°C / -25°C / -40°C'],['압축기 라인업','Bitzer 2-Stage Semi-Hermetic'],['제상 시스템','살수식 (Water Defrosting Loop)'],['안전 및 제어','유압 보호 인터록 및 히팅 케이블']],accent:'sky',cta:'냉동창고 용량 설계 의뢰'},
  cdu:{label:'AI Data Center Liquid Cooling',title:'데이터센터 액체냉각 분배장치(CDU) & STS316L 배관',desc:'초고밀도 GPU/AI 서버 랙 발열 해소를 위한 Direct-to-Chip 액체냉각 인프라입니다. STS316L 위생 파이프의 오비탈 자동 TIG 용접과 화학 세정 부동태화 공정으로 파티클 및 부식을 방지합니다.',features:[['오비탈 자동 TIG 용접','비드 균일도 100% 확보 및 틈새 부식 방지'],['부동태화 화학 세정','산화 피막 형성을 통한 고순도 냉매 유지']],spec:[['배관 재질 규격','STS304 / STS316L Sanitary'],['용접 공법','Closed Chamber Orbital TIG'],['유체 규격','DOWFROST LC 25% / PG 솔루션'],['밸브 제어','Belimo 정밀 에너지 밸브 (차압 제어)']],accent:'indigo',cta:'CDU 특수배관 기술 시방서 문의'}
};
function renderBusiness(tab='cleanroom') { const d=businessData[tab]||businessData.cleanroom; const tabs=[['cleanroom','산업·바이오 클린룸'],['dryroom','초저습 드라이룸'],['ref','냉동공학 & 저온물류'],['cdu','데이터센터 액체냉각 (CDU)']]; layout(`<section class="business-page"><div class="page-head business-heading"><p class="eyebrow">OUR CORE BUSINESS</p><h1>첨단 산업을 선도하는 엔지니어링 솔루션</h1><p>산업별 공조 및 유틸리티 기준을 오차 없이 완벽하게 구축합니다.</p></div><div class="business-tabs">${tabs.map(([id,label])=>`<button class="business-tab ${id===tab?'active':''}" data-business-tab="${id}">${label}</button>`).join('')}</div><article class="business-detail"><div class="business-copy"><span class="business-kicker ${d.accent}">${d.label}</span><h2>${d.title}</h2><p>${d.desc}</p><div class="business-features">${d.features.map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div><a class="business-cta" href="#/contact">${d.cta} →</a></div><div class="business-spec"><span>// STANDARD SPECIFICATIONS</span>${d.spec.map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}<em>현장 조건에 맞춘 맞춤 엔지니어링</em></div></article></section>`); document.querySelectorAll('[data-business-tab]').forEach(b=>b.onclick=()=>renderBusiness(b.dataset.businessTab)); }

function renderContact() { layout(`<section class="page-head"><p class="eyebrow">CONTACT</p><h1>견적문의</h1><p>프로젝트 내용을 남겨주시면 담당자가 확인 후 연락드립니다.</p></section><section class="form-wrap"><form id="inquiry-form"><label>회사명 *<input name="company" required></label><label>담당자명 *<input name="name" required></label><div class="form-row"><label>연락처 *<input name="phone" required></label><label>이메일<input name="email" type="email"></label></div><label>문의 유형<select name="inquiry_type"><option>클린룸 신축 문의</option><option>냉난방 공조 문의</option><option>유지보수 문의</option><option>기타</option></select></label><label>문의 내용 *<textarea name="message" rows="7" required></textarea></label><button class="button" type="submit">문의 접수하기</button></form></section>`); document.querySelector('#inquiry-form').addEventListener('submit', async e=>{e.preventDefault(); const f=new FormData(e.target); const row=Object.fromEntries(f.entries()); const {error}=await db.from('inquiries').insert(row); if(error){toast('문의 접수에 실패했습니다.');return} e.target.reset(); toast('문의가 접수되었습니다. 빠른 시일 내 연락드리겠습니다.');}); }

async function visitorStats() {
  const { data, error } = await db.from('page_view_counts').select('view_date,path,view_count').order('view_date',{ascending:false}).limit(10000);
  if (error) return {total:0,today:0,month:0,pages:[]};
  const rows=data||[], now=new Date(), todayKey=now.toISOString().slice(0,10), monthKey=now.toISOString().slice(0,7);
  const total=rows.reduce((n,x)=>n+Number(x.view_count||0),0), today=rows.filter(x=>x.view_date===todayKey).reduce((n,x)=>n+Number(x.view_count||0),0), month=rows.filter(x=>x.view_date?.slice(0,7)===monthKey).reduce((n,x)=>n+Number(x.view_count||0),0);
  const pages=Object.entries(rows.reduce((a,x)=>{a[x.path]=(a[x.path]||0)+Number(x.view_count||0);return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,5);
  return {total,today,month,pages};
}
function statsPanel(s) { return `<section class="stats-grid"><div class="stat-card"><span>오늘 조회수</span><b>${s.today}</b><small>페이지 조회</small></div><div class="stat-card"><span>이번 달 조회수</span><b>${s.month}</b><small>페이지 조회</small></div><div class="stat-card"><span>누적 조회수</span><b>${s.total}</b><small>페이지 조회</small></div><div class="stat-card"><span>집계 기준</span><b>숫자</b><small>개인정보 미수집</small></div></section><section class="panel stats-panel"><div class="panel-title"><h2>인기 페이지</h2><small>페이지 조회 수</small></div>${s.pages.map(([path,count])=>`<div class="stat-row"><span>${esc(path)}</span><b>${count}</b></div>`).join('')||'<div class="empty">아직 방문 기록이 없습니다.</div>'}</section>`; }
async function getAdmin() { const {data:{user}}=await db.auth.getUser(); if(!user) return null; const {data,error}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle(); return error?null:(data?.role==='admin'?user:null); }
function loginView() { layout(`<section class="auth"><div class="auth-card"><img src="/assets/isang-eng-logo.png" alt="ISANG ENG" class="auth-logo"><h1>관리자 로그인</h1><p>관리자 계정으로 로그인하세요.</p><form id="login-form"><input name="email" type="email" placeholder="이메일" required><input name="password" type="password" placeholder="비밀번호" required><button class="button" type="submit">로그인</button></form><a href="#/">홈으로 돌아가기</a></div></section>`); document.querySelector('#login-form').addEventListener('submit', async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)toast('이메일 또는 비밀번호를 확인하세요.');else renderAdmin();}); }
async function renderAdmin() { const user=await getAdmin(); if(!user){loginView();return} let rows=[]; try {rows=await projects()}catch{} const {data:inq=[]}=await db.from('inquiries').select('*').order('created_at',{ascending:false}).limit(100); const stats=await visitorStats(); layout(`<section class="admin-head"><div><p class="eyebrow">ADMIN DASHBOARD</p><h1>관리자 홈페이지</h1><p>${esc(user.email)}</p></div><button id="logout" class="button secondary">로그아웃</button></section>${statsPanel(stats)}<section class="admin-grid"><div class="panel"><div class="panel-title"><h2>시공사례 관리</h2><button id="add-project" class="button small">새 사례 등록</button></div><div id="project-list">${rows.map(x=>`<div class="admin-row"><div><b>${esc(x.name)}</b><small>${esc(x.year)} · ${esc(x.client||'')}</small></div><button data-edit="${x.id}" class="text-btn">수정</button><button data-delete="${x.id}" class="text-btn danger">삭제</button></div>`).join('')||'<div class="empty">등록된 사례가 없습니다.</div>'}</div></div><div class="panel"><h2>견적문의</h2>${(inq||[]).map(x=>`<div class="inquiry"><b>${esc(x.company)} / ${esc(x.name)}</b><small>${esc(x.phone)} · ${esc(x.created_at?.slice(0,10))} · ${esc(x.status)}</small><p>${esc(x.message)}</p></div>`).join('')||'<div class="empty">접수된 문의가 없습니다.</div>'}</div></section>`); document.querySelector('#logout').onclick=async()=>{await db.auth.signOut();renderAdmin()}; document.querySelector('#add-project').onclick=()=>projectDialog(); document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>projectDialog(rows.find(x=>String(x.id)===b.dataset.edit))); document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('삭제하시겠습니까?'))return;const {error}=await db.from('projects').delete().eq('id',b.dataset.delete);if(error)toast('삭제 실패');else renderAdmin()}); }
function projectDialog(row={}) { const d=document.createElement('dialog');d.innerHTML=`<form method="dialog" id="project-form"><h2>${row.id?'시공사례 수정':'시공사례 등록'}</h2><input name="year" placeholder="연도" value="${esc(row.year||new Date().getFullYear())}" required><input name="name" placeholder="프로젝트명" value="${esc(row.name||'')}" required><input name="client" placeholder="발주처" value="${esc(row.client||'')}"><input name="location" placeholder="위치" value="${esc(row.location||'')}"><input name="project_type" placeholder="프로젝트 유형" value="${esc(row.project_type||'')}"><input name="grade" placeholder="등급" value="${esc(row.grade||'')}"><textarea name="description" placeholder="설명">${esc(row.description||'')}</textarea><div class="dialog-actions"><button value="cancel">취소</button><button class="button" type="submit">저장</button></div></form>`;document.body.appendChild(d);d.showModal();d.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const rowData=Object.fromEntries(new FormData(e.target).entries());const q=row.id?db.from('projects').update(rowData).eq('id',row.id):db.from('projects').insert(rowData);const {error}=await q;if(error)toast('저장 실패');else{d.close();d.remove();renderAdmin()}});d.addEventListener('close',()=>d.remove()); }

async function route(){const p=location.hash.replace('#','')||'/'; if(p==='/projects')return renderProjects(); if(p==='/business')return renderBusiness(); if(p==='/contact')return renderContact(); if(p==='/admin')return renderAdmin(); return renderHome();}
window.addEventListener('hashchange',route); db.auth.onAuthStateChange(()=>{if(location.hash==='#/admin')renderAdmin()}); route();
