const SUPABASE_URL = 'https://knormndeorczxgwqvkol.supabase.co';
const SUPABASE_KEY = 'sb_publishable_Dx6cuRP7CgJUwQlj67OFyQ_viNQ1SyL';
const { createClient } = window.supabase;
const db = createClient(SUPABASE_URL, SUPABASE_KEY);
const app = document.querySelector('#app');

const logo = `<img src="/assets/isang-eng-logo.png" alt="ISANG ENG 이상이엔지" class="logo">`;
const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav = () => `<header><a href="#/">${logo}</a><nav><a href="#/">홈</a><a href="#/projects">시공사례</a><a href="#/contact">견적문의</a><a href="#/admin">관리자</a></nav></header>`;
const toast = msg => { const el = document.createElement('div'); el.className='toast'; el.textContent=msg; document.body.appendChild(el); setTimeout(()=>el.remove(), 3200); };

async function projects() {
  const { data, error } = await db.from('projects').select('*').order('year',{ascending:false}).limit(100);
  if (error) throw error; return data || [];
}

function layout(content) { app.innerHTML = nav() + `<main>${content}</main><footer>© ${new Date().getFullYear()} ISANG ENGINEERING. All rights reserved.</footer>`; }

async function renderHome() {
  layout(`<section class="hero"><div><p class="eyebrow">HVAC · CLEANROOM · ENGINEERING</p><h1>정밀한 기술로<br><strong>더 나은 환경</strong>을 만듭니다.</h1><p class="lead">냉난방 공조와 크린룸 설계·시공 전문기업 이상이엔지입니다.</p><a class="button" href="#/contact">견적문의하기</a></div><div class="hero-card"><span>01</span><b>Precision<br>Engineering</b><small>설계부터 시공, 유지관리까지</small></div></section><section class="section"><p class="eyebrow">WHAT WE DO</p><h2>공간의 기준을 설계합니다</h2><div class="cards"><article><b>HVAC</b><p>쾌적하고 안정적인 냉난방 공조 시스템</p></article><article><b>CLEANROOM</b><p>산업별 요구조건에 맞춘 크린룸 엔지니어링</p></article><article><b>PROJECT</b><p>현장 경험과 데이터로 완성하는 시공</p></article></div></section>`);
}

async function renderProjects() {
  try { const rows = await projects(); layout(`<section class="page-head"><p class="eyebrow">PROJECTS</p><h1>시공사례</h1><p>이상이엔지가 완성한 주요 프로젝트입니다.</p></section><section class="project-grid">${rows.length ? rows.map(x=>`<article class="project"><div class="project-no">${esc(x.year||'—')}</div><h3>${esc(x.name)}</h3><p>${esc(x.client||'')} ${x.location?`· ${esc(x.location)}`:''}</p><small>${esc(x.project_type||'')} ${x.grade?`· ${esc(x.grade)}`:''}</small><div>${esc(x.description||'')}</div></article>`).join('') : '<div class="empty">등록된 시공사례가 없습니다.</div>'}</section>`); }
  catch(e) { layout(`<section class="page-head"><h1>시공사례</h1><div class="error">데이터를 불러오지 못했습니다. Supabase 설정을 확인해 주세요.</div></section>`); }
}

function renderContact() { layout(`<section class="page-head"><p class="eyebrow">CONTACT</p><h1>견적문의</h1><p>프로젝트 내용을 남겨주시면 담당자가 확인 후 연락드립니다.</p></section><section class="form-wrap"><form id="inquiry-form"><label>회사명 *<input name="company" required></label><label>담당자명 *<input name="name" required></label><div class="form-row"><label>연락처 *<input name="phone" required></label><label>이메일<input name="email" type="email"></label></div><label>문의 유형<select name="inquiry_type"><option>클린룸 신축 문의</option><option>냉난방 공조 문의</option><option>유지보수 문의</option><option>기타</option></select></label><label>문의 내용 *<textarea name="message" rows="7" required></textarea></label><button class="button" type="submit">문의 접수하기</button></form></section>`); document.querySelector('#inquiry-form').addEventListener('submit', async e=>{e.preventDefault(); const f=new FormData(e.target); const row=Object.fromEntries(f.entries()); const {error}=await db.from('inquiries').insert(row); if(error){toast('문의 접수에 실패했습니다.');return} e.target.reset(); toast('문의가 접수되었습니다. 빠른 시일 내 연락드리겠습니다.');}); }

async function getAdmin() { const {data:{user}}=await db.auth.getUser(); if(!user) return null; const {data,error}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle(); return error?null:(data?.role==='admin'?user:null); }
function loginView() { layout(`<section class="auth"><div class="auth-card"><img src="/assets/isang-eng-logo.png" alt="ISANG ENG" class="auth-logo"><h1>관리자 로그인</h1><p>관리자 계정으로 로그인하세요.</p><form id="login-form"><input name="email" type="email" placeholder="이메일" required><input name="password" type="password" placeholder="비밀번호" required><button class="button" type="submit">로그인</button></form><a href="#/">홈으로 돌아가기</a></div></section>`); document.querySelector('#login-form').addEventListener('submit', async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)toast('이메일 또는 비밀번호를 확인하세요.');else renderAdmin();}); }
async function renderAdmin() { const user=await getAdmin(); if(!user){loginView();return} let rows=[]; try {rows=await projects()}catch{} const {data:inq=[]}=await db.from('inquiries').select('*').order('created_at',{ascending:false}).limit(100); layout(`<section class="admin-head"><div><p class="eyebrow">ADMIN DASHBOARD</p><h1>관리자 홈페이지</h1><p>${esc(user.email)}</p></div><button id="logout" class="button secondary">로그아웃</button></section><section class="admin-grid"><div class="panel"><div class="panel-title"><h2>시공사례 관리</h2><button id="add-project" class="button small">새 사례 등록</button></div><div id="project-list">${rows.map(x=>`<div class="admin-row"><div><b>${esc(x.name)}</b><small>${esc(x.year)} · ${esc(x.client||'')}</small></div><button data-edit="${x.id}" class="text-btn">수정</button><button data-delete="${x.id}" class="text-btn danger">삭제</button></div>`).join('')||'<div class="empty">등록된 사례가 없습니다.</div>'}</div></div><div class="panel"><h2>견적문의</h2>${(inq||[]).map(x=>`<div class="inquiry"><b>${esc(x.company)} / ${esc(x.name)}</b><small>${esc(x.phone)} · ${esc(x.created_at?.slice(0,10))} · ${esc(x.status)}</small><p>${esc(x.message)}</p></div>`).join('')||'<div class="empty">접수된 문의가 없습니다.</div>'}</div></section>`); document.querySelector('#logout').onclick=async()=>{await db.auth.signOut();renderAdmin()}; document.querySelector('#add-project').onclick=()=>projectDialog(); document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>projectDialog(rows.find(x=>String(x.id)===b.dataset.edit))); document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('삭제하시겠습니까?'))return;const {error}=await db.from('projects').delete().eq('id',b.dataset.delete);if(error)toast('삭제 실패');else renderAdmin()}); }
function projectDialog(row={}) { const d=document.createElement('dialog');d.innerHTML=`<form method="dialog" id="project-form"><h2>${row.id?'시공사례 수정':'시공사례 등록'}</h2><input name="year" placeholder="연도" value="${esc(row.year||new Date().getFullYear())}" required><input name="name" placeholder="프로젝트명" value="${esc(row.name||'')}" required><input name="client" placeholder="발주처" value="${esc(row.client||'')}"><input name="location" placeholder="위치" value="${esc(row.location||'')}"><input name="project_type" placeholder="프로젝트 유형" value="${esc(row.project_type||'')}"><input name="grade" placeholder="등급" value="${esc(row.grade||'')}"><textarea name="description" placeholder="설명">${esc(row.description||'')}</textarea><div class="dialog-actions"><button value="cancel">취소</button><button class="button" type="submit">저장</button></div></form>`;document.body.appendChild(d);d.showModal();d.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const rowData=Object.fromEntries(new FormData(e.target).entries());const q=row.id?db.from('projects').update(rowData).eq('id',row.id):db.from('projects').insert(rowData);const {error}=await q;if(error)toast('저장 실패');else{d.close();d.remove();renderAdmin()}});d.addEventListener('close',()=>d.remove()); }

async function route(){const p=location.hash.replace('#','')||'/'; if(p==='/projects')return renderProjects(); if(p==='/contact')return renderContact(); if(p==='/admin')return renderAdmin(); return renderHome();}
window.addEventListener('hashchange',route); db.auth.onAuthStateChange(()=>{if(location.hash==='#/admin')renderAdmin()}); route();
